@startuml
left to right direction
skinparam packageStyle rectangle

actor "사용자" as User
actor "Source\n연계 시스템" as Src << actor >>
actor "Destination\n연계 시스템" as Dst << actor >>

rectangle "단방향 전송 시스템" as UTG_SYS {
rectangle "단방향 전송 서비스" as UTG_SVC {
    usecase "연계 프록시 연동" as Proxy
    usecase "프로토콜 식별 및 통제" as ProtoClassify
    usecase "데이터 무결성 검증" as DataIntegrityChk
    usecase "데이터 암호화/복호화" as DataEncDec
    usecase "데이터 캡슐화/역캡슐화" as DataEncapDecap
    usecase "단방향 데이터 전송" as UniDataTransfer

    (Proxy) .> (ProtoClassify) : <<include>>
    (ProtoClassify) .> (DataIntegrityChk) : <<include>>
    (DataIntegrityChk) .> (DataEncapDecap) : <<include>>
    (DataEncapDecap) .> (DataEncDec) : <<include>>
    (DataEncDec) .> (UniDataTransfer) : <<include>>
}

rectangle "공통 코어 서비스" as CORE_SVC {
    usecase "서비스 관리" as svcmgmt
    usecase "시스템 관리" as sysmgmt
    usecase "보안 관리" as secmgmt
    usecase "감사 관리" as auditmgmt
    usecase "통계 관리" as statmgmt
    usecase "사용자 관리" as usermgmt
    usecase "알람 관리" as alarmmgmt
    usecase "시스템 환경 설정 관리" as sysenvmgmt

    (svcmgmt) .> (sysmgmt) : <<include>>
    (auditmgmt) <. (alarmmgmt) : <<extend>>
}

}

User -- UTG_SYS
Src -- UTG_SYS
UTG_SYS -- Dst
UTG_SVC -- CORE_SVC
@enduml