@startuml
left to right direction
"Admin" as admin << Human >>
"Operator" as operator << Human >>
"연계서비스" as src << Source >>
"연계서비스" as dst << Destination >>

package "단방향전송시스템" as UTG_System {
    usecase "서비스등록" as UC1
    usecase "감사조회" as UC2
    usecase "통계조회" as UC3
    usecase "사용자등록" as UC4
    usecase "로그인" as UC5
}

admin --> UC1
admin --> UC2
admin --> UC3
admin --> UC4
operator --> UC2
operator --> UC3
src --> UTG_System
UTG_System --> dst
UC1 .> UC5 : include
UC2 .> UC5 : include
UC3 .> UC5 : include
UC4 .> UC5 : include

@enduml