@startuml
|#pink|데이터 처리부|
start
:연계 서비스 연결;
repeat
    :데이터 수집;
    :프로토콜 식별 및 통제;
    :데이터 무결성 검증;
    :데이터 캡슐화;
|#lightgray|데이터 전송부|
    if (암호화?) then (yes)
        :데이터 암호화;
    endif
    :단방향 데이터 송신;
    :단방향 데이터 수신;
    if (암호화?) then (yes)
        :데이터 복호화;
    endif
|#pink|데이터 처리부|
    :데이터 무결성 검증;
    :데이터 역캡슐화;
    :프로토콜 분류;
    :연계 서비스 데이터 전달;
repeatwhile
@enduml